//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaLocationDeVoiture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int id_reservation { get; set; }
        public string matricule { get; set; }
        public string cin { get; set; }
        public Nullable<System.DateTime> date_deb { get; set; }
        public Nullable<int> nbr_jour { get; set; }
        public string lieu_deb { get; set; }
        public string lieu_fin { get; set; }
        public Nullable<double> montant { get; set; }
    }
}
