//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaLocationDeVoiture.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User
    {
        public int id_user { get; set; }
        public string cin { get; set; }
        public string user_name { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string tel { get; set; }
        public string num_permis { get; set; }
        public string email { get; set; }
        public string mot_pass { get; set; }
        public Nullable<int> role { get; set; }
        
        public User()
        {
            role = 1;
        }
    }
}
